// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fcff87f08acf04c0d1a0b4037d3460cffe910220d877abb336d800cfce215818
// Version: v1.3.3 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BlindedExecutionPayloadEnvelope](`ssz-static:"true"`)

// MarshalSSZ marshals the *BlindedExecutionPayloadEnvelope to SSZ-encoded bytes.
func (t *BlindedExecutionPayloadEnvelope) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BlindedExecutionPayloadEnvelope to SSZ-encoded bytes, appending to the provided buffer.
func (t *BlindedExecutionPayloadEnvelope) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlindedExecutionPayloadEnvelope)
	}
	{ // Static Field #0 'PayloadRoot'
		dst = append(dst, t.PayloadRoot[:32]...)
	}
	{ // Static Field #1 'ExecutionRequestsRoot'
		dst = append(dst, t.ExecutionRequestsRoot[:32]...)
	}
	{ // Static Field #2 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	{ // Static Field #3 'BeaconBlockRoot'
		dst = append(dst, t.BeaconBlockRoot[:32]...)
	}
	{ // Static Field #4 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BlindedExecutionPayloadEnvelope from SSZ-encoded bytes.
func (t *BlindedExecutionPayloadEnvelope) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 136 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 136)
	}
	if buflen > 136 {
		return sszutils.ErrTrailingDataFn(buflen - 136)
	}
	{ // Field #0 'PayloadRoot' (static)
		buf := buf[0:32]
		copy(t.PayloadRoot[:], buf)
	}
	{ // Field #1 'ExecutionRequestsRoot' (static)
		buf := buf[32:64]
		copy(t.ExecutionRequestsRoot[:], buf)
	}
	{ // Field #2 'BuilderIndex' (static)
		buf := buf[64:72]
		t.BuilderIndex = BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'BeaconBlockRoot' (static)
		buf := buf[72:104]
		copy(t.BeaconBlockRoot[:], buf)
	}
	{ // Field #4 'ParentBeaconBlockRoot' (static)
		buf := buf[104:136]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BlindedExecutionPayloadEnvelope.
func (t *BlindedExecutionPayloadEnvelope) SizeSSZ() (size int) {
	return 136
}

// HashTreeRoot computes the SSZ hash tree root of the *BlindedExecutionPayloadEnvelope.
func (t *BlindedExecutionPayloadEnvelope) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BlindedExecutionPayloadEnvelope using the given hash walker.
func (t *BlindedExecutionPayloadEnvelope) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlindedExecutionPayloadEnvelope)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'PayloadRoot'
		hh.PutBytes(t.PayloadRoot[:32])
	}
	{ // Field #1 'ExecutionRequestsRoot'
		hh.PutBytes(t.ExecutionRequestsRoot[:32])
	}
	{ // Field #2 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	{ // Field #3 'BeaconBlockRoot'
		hh.PutBytes(t.BeaconBlockRoot[:32])
	}
	{ // Field #4 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	hh.MerkleizeProgressiveWithActiveFields(idx, []byte{0x1f})
	return nil
}
