// Code generated by fastssz. DO NOT EDIT.
// Hash: beb05c8e5b759d253ba70b9a88df552d72bd25ead3b17162cae65141d3474bd1
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BuilderRequestAuth object
func (b *BuilderRequestAuth) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderRequestAuth object to a target array
func (b *BuilderRequestAuth) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Offset (0) 'Data'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(b.Slot))

	// Field (0) 'Data'
	if size := len(b.Data); size > 4096 {
		err = ssz.ErrBytesLengthFn("BuilderRequestAuth.Data", size, 4096)
		return
	}
	dst = append(dst, b.Data...)

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderRequestAuth object
func (b *BuilderRequestAuth) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Data'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Slot'
	b.Slot = phase0.Slot(ssz.UnmarshallUint64(buf[4:12]))

	// Field (0) 'Data'
	{
		buf = tail[o0:]
		if len(buf) > 4096 {
			return ssz.ErrBytesLength
		}
		if cap(b.Data) == 0 {
			b.Data = make([]byte, 0, len(buf))
		}
		b.Data = append(b.Data, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderRequestAuth object
func (b *BuilderRequestAuth) SizeSSZ() (size int) {
	size = 12

	// Field (0) 'Data'
	size += len(b.Data)

	return
}

// HashTreeRoot ssz hashes the BuilderRequestAuth object
func (b *BuilderRequestAuth) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderRequestAuth object with a hasher
func (b *BuilderRequestAuth) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(b.Data))
		if byteLen > 4096 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(b.Data)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (4096+31)/32)
	}

	// Field (1) 'Slot'
	hh.PutUint64(uint64(b.Slot))

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BuilderRequestAuth object
func (b *BuilderRequestAuth) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the SignedBuilderRequestAuth object
func (s *SignedBuilderRequestAuth) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedBuilderRequestAuth object to a target array
func (s *SignedBuilderRequestAuth) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedBuilderRequestAuth object
func (s *SignedBuilderRequestAuth) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[4:100])

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if s.Message == nil {
			s.Message = new(BuilderRequestAuth)
		}
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedBuilderRequestAuth object
func (s *SignedBuilderRequestAuth) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(BuilderRequestAuth)
	}
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedBuilderRequestAuth object
func (s *SignedBuilderRequestAuth) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedBuilderRequestAuth object with a hasher
func (s *SignedBuilderRequestAuth) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedBuilderRequestAuth object
func (s *SignedBuilderRequestAuth) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
