// Code generated by fastssz. DO NOT EDIT.
// Hash: 204d63accd7890827e1248f1ae978907d4dd85be06fbe774adbd083d82c8408d
// Version: 0.1.3
package gloas

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlindedExecutionPayloadEnvelope object to a target array
func (b *BlindedExecutionPayloadEnvelope) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'PayloadRoot'
	dst = append(dst, b.PayloadRoot[:]...)

	// Field (1) 'ExecutionRequestsRoot'
	dst = append(dst, b.ExecutionRequestsRoot[:]...)

	// Field (2) 'BuilderIndex'
	dst = ssz.MarshalUint64(dst, uint64(b.BuilderIndex))

	// Field (3) 'BeaconBlockRoot'
	dst = append(dst, b.BeaconBlockRoot[:]...)

	// Field (4) 'ParentBeaconBlockRoot'
	dst = append(dst, b.ParentBeaconBlockRoot[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 136 {
		return ssz.ErrSize
	}

	// Field (0) 'PayloadRoot'
	copy(b.PayloadRoot[:], buf[0:32])

	// Field (1) 'ExecutionRequestsRoot'
	copy(b.ExecutionRequestsRoot[:], buf[32:64])

	// Field (2) 'BuilderIndex'
	b.BuilderIndex = BuilderIndex(ssz.UnmarshallUint64(buf[64:72]))

	// Field (3) 'BeaconBlockRoot'
	copy(b.BeaconBlockRoot[:], buf[72:104])

	// Field (4) 'ParentBeaconBlockRoot'
	copy(b.ParentBeaconBlockRoot[:], buf[104:136])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) SizeSSZ() (size int) {
	size = 136
	return
}

// HashTreeRoot ssz hashes the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlindedExecutionPayloadEnvelope object with a hasher
func (b *BlindedExecutionPayloadEnvelope) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'PayloadRoot'
	hh.PutBytes(b.PayloadRoot[:])

	// Field (1) 'ExecutionRequestsRoot'
	hh.PutBytes(b.ExecutionRequestsRoot[:])

	// Field (2) 'BuilderIndex'
	hh.PutUint64(uint64(b.BuilderIndex))

	// Field (3) 'BeaconBlockRoot'
	hh.PutBytes(b.BeaconBlockRoot[:])

	// Field (4) 'ParentBeaconBlockRoot'
	hh.PutBytes(b.ParentBeaconBlockRoot[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
