// Code generated by fastssz. DO NOT EDIT.
// Hash: 78c04e3bf1d263866423d18dac8ae5c778032bb99644a9b339520a8ea571a7a7
// Version: 0.1.3
package gloas

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlindedExecutionPayloadEnvelope object to a target array
func (b *BlindedExecutionPayloadEnvelope) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(108)

	// Field (0) 'PayloadRoot'
	dst = append(dst, b.PayloadRoot[:]...)

	// Offset (1) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)

	// Field (2) 'BuilderIndex'
	dst = ssz.MarshalUint64(dst, uint64(b.BuilderIndex))

	// Field (3) 'BeaconBlockRoot'
	dst = append(dst, b.BeaconBlockRoot[:]...)

	// Field (4) 'ParentBeaconBlockRoot'
	dst = append(dst, b.ParentBeaconBlockRoot[:]...)

	// Field (1) 'ExecutionRequests'
	if dst, err = b.ExecutionRequests.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 108 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'PayloadRoot'
	copy(b.PayloadRoot[:], buf[0:32])

	// Offset (1) 'ExecutionRequests'
	if o1 = ssz.ReadOffset(buf[32:36]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 108 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (2) 'BuilderIndex'
	b.BuilderIndex = BuilderIndex(ssz.UnmarshallUint64(buf[36:44]))

	// Field (3) 'BeaconBlockRoot'
	copy(b.BeaconBlockRoot[:], buf[44:76])

	// Field (4) 'ParentBeaconBlockRoot'
	copy(b.ParentBeaconBlockRoot[:], buf[76:108])

	// Field (1) 'ExecutionRequests'
	{
		buf = tail[o1:]
		if b.ExecutionRequests == nil {
			b.ExecutionRequests = new(ExecutionRequests)
		}
		if err = b.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) SizeSSZ() (size int) {
	size = 108

	// Field (1) 'ExecutionRequests'
	if b.ExecutionRequests == nil {
		b.ExecutionRequests = new(ExecutionRequests)
	}
	size += b.ExecutionRequests.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlindedExecutionPayloadEnvelope object with a hasher
func (b *BlindedExecutionPayloadEnvelope) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'PayloadRoot'
	hh.PutBytes(b.PayloadRoot[:])

	// Field (1) 'ExecutionRequests'
	if err = b.ExecutionRequests.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'BuilderIndex'
	hh.PutUint64(uint64(b.BuilderIndex))

	// Field (3) 'BeaconBlockRoot'
	hh.PutBytes(b.BeaconBlockRoot[:])

	// Field (4) 'ParentBeaconBlockRoot'
	hh.PutBytes(b.ParentBeaconBlockRoot[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BlindedExecutionPayloadEnvelope object
func (b *BlindedExecutionPayloadEnvelope) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the SignedBlindedExecutionPayloadEnvelope object
func (s *SignedBlindedExecutionPayloadEnvelope) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedBlindedExecutionPayloadEnvelope object to a target array
func (s *SignedBlindedExecutionPayloadEnvelope) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedBlindedExecutionPayloadEnvelope object
func (s *SignedBlindedExecutionPayloadEnvelope) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[4:100])

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if s.Message == nil {
			s.Message = new(BlindedExecutionPayloadEnvelope)
		}
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedBlindedExecutionPayloadEnvelope object
func (s *SignedBlindedExecutionPayloadEnvelope) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(BlindedExecutionPayloadEnvelope)
	}
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedBlindedExecutionPayloadEnvelope object
func (s *SignedBlindedExecutionPayloadEnvelope) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedBlindedExecutionPayloadEnvelope object with a hasher
func (s *SignedBlindedExecutionPayloadEnvelope) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedBlindedExecutionPayloadEnvelope object
func (s *SignedBlindedExecutionPayloadEnvelope) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
