package gloas

// The Gloas SSZ types use progressive containers/lists (EIP-7688/7916), which fastssz cannot
// merkleize; their encoders are generated by pk910/dynamic-ssz instead. Regenerate with `go generate`.
// File naming in this package: hand-written type files are snake_case.go (e.g. beacon_block.go);
// the dynssz-generated encoders are flatcase *_ssz.go (e.g. beaconblock_ssz.go) — do not edit those.
//go:generate rm -f *_ssz.go
//go:generate go tool dynssz-gen -config generate.yaml
