// Code generated by fastssz. DO NOT EDIT.
// Hash: 6f31b540d41eab8b6838b076d85dd0851f013a6b996b6fb11ebe010a9c7b0523
// Version: 0.1.3
package gloas

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the GloasProposalData object
func (g *GloasProposalData) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GloasProposalData object to a target array
func (g *GloasProposalData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(36)

	// Offset (0) 'Block'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'PayloadRoot'
	dst = append(dst, g.PayloadRoot[:]...)

	// Field (0) 'Block'
	if dst, err = g.Block.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the GloasProposalData object
func (g *GloasProposalData) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 36 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Block'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 36 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'PayloadRoot'
	copy(g.PayloadRoot[:], buf[4:36])

	// Field (0) 'Block'
	{
		buf = tail[o0:]
		if g.Block == nil {
			g.Block = new(BeaconBlock)
		}
		if err = g.Block.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GloasProposalData object
func (g *GloasProposalData) SizeSSZ() (size int) {
	size = 36

	// Field (0) 'Block'
	if g.Block == nil {
		g.Block = new(BeaconBlock)
	}
	size += g.Block.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the GloasProposalData object
func (g *GloasProposalData) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GloasProposalData object with a hasher
func (g *GloasProposalData) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Block'
	if err = g.Block.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'PayloadRoot'
	hh.PutBytes(g.PayloadRoot[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the GloasProposalData object
func (g *GloasProposalData) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(g)
}
