// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 3b99559911ce396f7f6769cf0d22899549dfb1bee3648a0537d6536491f838cd
// Version: v1.3.3 (https://github.com/pk910/dynamic-ssz)
package types

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[AggregatorCommitteeConsensusData](`ssz-static:"false"`)

// MarshalSSZ marshals the *AggregatorCommitteeConsensusData to SSZ-encoded bytes.
func (t *AggregatorCommitteeConsensusData) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *AggregatorCommitteeConsensusData to SSZ-encoded bytes, appending to the provided buffer.
func (t *AggregatorCommitteeConsensusData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(AggregatorCommitteeConsensusData)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Version'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Version))
	}
	// Offset Field #1 'Aggregators'
	// Offset Field #2 'AggregatorsCommitteeIndexes'
	// Offset Field #3 'AggregatedAttestations'
	// Offset Field #4 'Contributors'
	// Offset Field #5 'SyncCommitteeContributions'
	dst = append(dst, zeroBytes[:20]...)
	{ // Dynamic Field #1 'Aggregators'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Aggregators
		vlen := len(t)
		if vlen > 3000 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 3000), "Aggregators")
		}
		for idx1 := range vlen {
			t := &t[idx1]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Aggregators[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #2 'AggregatorsCommitteeIndexes'
		binary.LittleEndian.PutUint32(dst[dstlen+12:], uint32(len(dst)-dstlen))
		t := t.AggregatorsCommitteeIndexes
		vlen := len(t)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "AggregatorsCommitteeIndexes")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	{ // Dynamic Field #3 'AggregatedAttestations'
		binary.LittleEndian.PutUint32(dst[dstlen+16:], uint32(len(dst)-dstlen))
		t := t.AggregatedAttestations
		vlen := len(t)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "AggregatedAttestations")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > 131308 {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 131308), "AggregatedAttestations[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	{ // Dynamic Field #4 'Contributors'
		binary.LittleEndian.PutUint32(dst[dstlen+20:], uint32(len(dst)-dstlen))
		t := t.Contributors
		vlen := len(t)
		if vlen > 2048 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "Contributors")
		}
		for idx1 := range vlen {
			t := &t[idx1]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Contributors[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #5 'SyncCommitteeContributions'
		binary.LittleEndian.PutUint32(dst[dstlen+24:], uint32(len(dst)-dstlen))
		t := t.SyncCommitteeContributions
		vlen := len(t)
		if vlen > 4 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4), "SyncCommitteeContributions")
		}
		for idx1 := range vlen {
			t := &t[idx1]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "SyncCommitteeContributions[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *AggregatorCommitteeConsensusData from SSZ-encoded bytes.
func (t *AggregatorCommitteeConsensusData) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 28 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 28)
	}
	{ // Field #0 'Version' (static)
		buf := buf[0:8]
		t.Version = spec.DataVersion(binary.LittleEndian.Uint64(buf))
	}
	// Field #1 'Aggregators' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset1 != 28 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 28), "Aggregators:o")
	}
	// Field #2 'AggregatorsCommitteeIndexes' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[12:16]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "AggregatorsCommitteeIndexes:o")
	}
	// Field #3 'AggregatedAttestations' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[16:20]))
	if offset3 < offset2 || offset3 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset2, buflen), "AggregatedAttestations:o")
	}
	// Field #4 'Contributors' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[20:24]))
	if offset4 < offset3 || offset4 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset3, buflen), "Contributors:o")
	}
	// Field #5 'SyncCommitteeContributions' (offset)
	offset5 := int(binary.LittleEndian.Uint32(buf[24:28]))
	if offset5 < offset4 || offset5 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset5, offset4, buflen), "SyncCommitteeContributions:o")
	}
	{ // Field #1 'Aggregators' (dynamic)
		buf := buf[offset1:offset2]
		val1 := t.Aggregators
		itemCount := len(buf) / 112
		if len(buf)%112 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 112), "Aggregators")
		}
		if itemCount > 3000 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 3000), "Aggregators")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[112*idx1 : 112*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Aggregators[%d]", idx1)
			}
		}
		t.Aggregators = val1
	}
	{ // Field #2 'AggregatorsCommitteeIndexes' (dynamic)
		buf := buf[offset2:offset3]
		val2 := t.AggregatorsCommitteeIndexes
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "AggregatorsCommitteeIndexes")
		}
		if itemCount > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 64), "AggregatorsCommitteeIndexes")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		sszutils.UnmarshalUint64Slice(val2, buf)
		t.AggregatorsCommitteeIndexes = val2
	}
	{ // Field #3 'AggregatedAttestations' (dynamic)
		buf := buf[offset3:offset4]
		val3 := t.AggregatedAttestations
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "AggregatedAttestations")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "AggregatedAttestations")
		}
		if itemCount > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 64), "AggregatedAttestations")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "AggregatedAttestations[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val4 := val3[idx1]
			if len(buf) > 131308 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), 131308), "AggregatedAttestations[%d]", idx1)
			}
			val4 = sszutils.ExpandSlice(val4, len(buf))
			copy(val4[:], buf)
			val3[idx1] = val4
		}
		t.AggregatedAttestations = val3
	}
	{ // Field #4 'Contributors' (dynamic)
		buf := buf[offset4:offset5]
		val5 := t.Contributors
		itemCount := len(buf) / 112
		if len(buf)%112 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 112), "Contributors")
		}
		if itemCount > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 2048), "Contributors")
		}
		val5 = sszutils.ExpandSlice(val5, itemCount)
		for idx1 := range itemCount {
			buf := buf[112*idx1 : 112*(idx1+1)]
			if err = val5[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Contributors[%d]", idx1)
			}
		}
		t.Contributors = val5
	}
	{ // Field #5 'SyncCommitteeContributions' (dynamic)
		buf := buf[offset5:]
		val6 := t.SyncCommitteeContributions
		itemCount := len(buf) / 160
		if len(buf)%160 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 160), "SyncCommitteeContributions")
		}
		if itemCount > 4 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4), "SyncCommitteeContributions")
		}
		val6 = sszutils.ExpandSlice(val6, itemCount)
		for idx1 := range itemCount {
			buf := buf[160*idx1 : 160*(idx1+1)]
			if err = val6[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "SyncCommitteeContributions[%d]", idx1)
			}
		}
		t.SyncCommitteeContributions = val6
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *AggregatorCommitteeConsensusData.
func (t *AggregatorCommitteeConsensusData) SizeSSZ() (size int) {
	if t == nil {
		t = new(AggregatorCommitteeConsensusData)
	}
	// Field #0 'Version' static (8 bytes)
	// Field #1 'Aggregators' offset (4 bytes)
	// Field #2 'AggregatorsCommitteeIndexes' offset (4 bytes)
	// Field #3 'AggregatedAttestations' offset (4 bytes)
	// Field #4 'Contributors' offset (4 bytes)
	// Field #5 'SyncCommitteeContributions' offset (4 bytes)
	size += 28
	{ // Dynamic field #1 'Aggregators'
		size += len(t.Aggregators) * 112
	}
	{ // Dynamic field #2 'AggregatorsCommitteeIndexes'
		size += len(t.AggregatorsCommitteeIndexes) * 8
	}
	{ // Dynamic field #3 'AggregatedAttestations'
		t := t.AggregatedAttestations
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	{ // Dynamic field #4 'Contributors'
		size += len(t.Contributors) * 112
	}
	{ // Dynamic field #5 'SyncCommitteeContributions'
		size += len(t.SyncCommitteeContributions) * 160
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *AggregatorCommitteeConsensusData.
func (t *AggregatorCommitteeConsensusData) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *AggregatorCommitteeConsensusData using the given hash walker.
func (t *AggregatorCommitteeConsensusData) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(AggregatorCommitteeConsensusData)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Version'
		hh.PutUint64(uint64(t.Version))
	}
	{ // Field #1 'Aggregators'
		t := t.Aggregators
		vlen := uint64(len(t))
		if vlen > 3000 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 3000), "Aggregators")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := &t[idx1]
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Aggregators[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(3000, vlen, 32))
	}
	{ // Field #2 'AggregatorsCommitteeIndexes'
		t := t.AggregatorsCommitteeIndexes
		vlen := uint64(len(t))
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "AggregatorsCommitteeIndexes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		sszutils.HashUint64Slice(hh, t)
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(64, vlen, 8))
	}
	{ // Field #3 'AggregatedAttestations'
		t := t.AggregatedAttestations
		vlen := uint64(len(t))
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "AggregatedAttestations")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > 131308 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 131308), "AggregatedAttestations[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(131308, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(64, vlen, 32))
	}
	{ // Field #4 'Contributors'
		t := t.Contributors
		vlen := uint64(len(t))
		if vlen > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "Contributors")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := &t[idx1]
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Contributors[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2048, vlen, 32))
	}
	{ // Field #5 'SyncCommitteeContributions'
		t := t.SyncCommitteeContributions
		vlen := uint64(len(t))
		if vlen > 4 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4), "SyncCommitteeContributions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := &t[idx1]
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "SyncCommitteeContributions[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
