// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b9b013ebdc54d08bfff8dce912fb15b18f527a1d34a1cc611e0a16d3a311fa94
// Version: v1.3.3 (https://github.com/pk910/dynamic-ssz)
package types

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[AssignedAggregator](`ssz-static:"true"`)

// MarshalSSZ marshals the *AssignedAggregator to SSZ-encoded bytes.
func (t *AssignedAggregator) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *AssignedAggregator to SSZ-encoded bytes, appending to the provided buffer.
func (t *AssignedAggregator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(AssignedAggregator)
	}
	{ // Static Field #0 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Static Field #1 'SelectionProof'
		dst = append(dst, t.SelectionProof[:96]...)
	}
	{ // Static Field #2 'CommitteeIndex'
		dst = binary.LittleEndian.AppendUint64(dst, t.CommitteeIndex)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *AssignedAggregator from SSZ-encoded bytes.
func (t *AssignedAggregator) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 112 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 112)
	}
	if buflen > 112 {
		return sszutils.ErrTrailingDataFn(buflen - 112)
	}
	{ // Field #0 'ValidatorIndex' (static)
		buf := buf[0:8]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'SelectionProof' (static)
		buf := buf[8:104]
		copy(t.SelectionProof[:], buf)
	}
	{ // Field #2 'CommitteeIndex' (static)
		buf := buf[104:112]
		t.CommitteeIndex = binary.LittleEndian.Uint64(buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *AssignedAggregator.
func (t *AssignedAggregator) SizeSSZ() (size int) {
	return 112
}

// HashTreeRoot computes the SSZ hash tree root of the *AssignedAggregator.
func (t *AssignedAggregator) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *AssignedAggregator using the given hash walker.
func (t *AssignedAggregator) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(AssignedAggregator)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #1 'SelectionProof'
		hh.PutBytes(t.SelectionProof[:96])
	}
	{ // Field #2 'CommitteeIndex'
		hh.PutUint64(t.CommitteeIndex)
	}
	hh.Merkleize(idx)
	return nil
}
