// Code generated by fastssz. DO NOT EDIT.
// Hash: c7be5e6d65946a25e347728301941ef55836a2e739afb601d2f3630ee7576fd4
package types

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Duty object
func (d *Duty) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(d)
}

// MarshalSSZTo ssz marshals the Duty object to a target array
func (d *Duty) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Type'
	dst = ssz.MarshalUint8(dst, uint8(d.Type))

	// Field (1) 'PubKey'
	dst = append(dst, d.PubKey[:]...)

	// Field (2) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(d.Slot))

	// Field (3) 'ValidatorIndex'
	dst = ssz.MarshalUint64(dst, uint64(d.ValidatorIndex))

	// Field (4) 'CommitteeIndex'
	dst = ssz.MarshalUint64(dst, uint64(d.CommitteeIndex))

	// Field (5) 'CommitteeLength'
	dst = ssz.MarshalUint64(dst, d.CommitteeLength)

	// Field (6) 'CommitteesAtSlot'
	dst = ssz.MarshalUint64(dst, d.CommitteesAtSlot)

	// Field (7) 'ValidatorCommitteeIndex'
	dst = ssz.MarshalUint64(dst, d.ValidatorCommitteeIndex)

	return
}

// UnmarshalSSZ ssz unmarshals the Duty object
func (d *Duty) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 97 {
		return ssz.ErrSize
	}

	// Field (0) 'Type'
	d.Type = BeaconRole(ssz.UnmarshallUint8(buf[0:1]))

	// Field (1) 'PubKey'
	copy(d.PubKey[:], buf[1:49])

	// Field (2) 'Slot'
	d.Slot = phase0.Slot(ssz.UnmarshallUint64(buf[49:57]))

	// Field (3) 'ValidatorIndex'
	d.ValidatorIndex = phase0.ValidatorIndex(ssz.UnmarshallUint64(buf[57:65]))

	// Field (4) 'CommitteeIndex'
	d.CommitteeIndex = phase0.CommitteeIndex(ssz.UnmarshallUint64(buf[65:73]))

	// Field (5) 'CommitteeLength'
	d.CommitteeLength = ssz.UnmarshallUint64(buf[73:81])

	// Field (6) 'CommitteesAtSlot'
	d.CommitteesAtSlot = ssz.UnmarshallUint64(buf[81:89])

	// Field (7) 'ValidatorCommitteeIndex'
	d.ValidatorCommitteeIndex = ssz.UnmarshallUint64(buf[89:97])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Duty object
func (d *Duty) SizeSSZ() (size int) {
	size = 97
	return
}

// HashTreeRoot ssz hashes the Duty object
func (d *Duty) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(d)
}

// HashTreeRootWith ssz hashes the Duty object with a hasher
func (d *Duty) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Type'
	hh.PutUint8(uint8(d.Type))

	// Field (1) 'PubKey'
	hh.PutBytes(d.PubKey[:])

	// Field (2) 'Slot'
	hh.PutUint64(uint64(d.Slot))

	// Field (3) 'ValidatorIndex'
	hh.PutUint64(uint64(d.ValidatorIndex))

	// Field (4) 'CommitteeIndex'
	hh.PutUint64(uint64(d.CommitteeIndex))

	// Field (5) 'CommitteeLength'
	hh.PutUint64(d.CommitteeLength)

	// Field (6) 'CommitteesAtSlot'
	hh.PutUint64(d.CommitteesAtSlot)

	// Field (7) 'ValidatorCommitteeIndex'
	hh.PutUint64(d.ValidatorCommitteeIndex)

	hh.Merkleize(indx)
	return
}
