// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 457ab6b3c0a9acae604f8fe54b90a1f608406f7159edbba2adbdd040947cfe97
// Version: v1.3.3 (https://github.com/pk910/dynamic-ssz)
package types

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BeaconVote](`ssz-static:"true"`)

// MarshalSSZ marshals the *BeaconVote to SSZ-encoded bytes.
func (t *BeaconVote) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BeaconVote to SSZ-encoded bytes, appending to the provided buffer.
func (t *BeaconVote) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconVote)
	}
	{ // Static Field #0 'BlockRoot'
		dst = append(dst, t.BlockRoot[:32]...)
	}
	{ // Static Field #1 'Source'
		t := t.Source
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Source")
		}
	}
	{ // Static Field #2 'Target'
		t := t.Target
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Target")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BeaconVote from SSZ-encoded bytes.
func (t *BeaconVote) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 112 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 112)
	}
	if buflen > 112 {
		return sszutils.ErrTrailingDataFn(buflen - 112)
	}
	{ // Field #0 'BlockRoot' (static)
		buf := buf[0:32]
		copy(t.BlockRoot[:], buf)
	}
	{ // Field #1 'Source' (static)
		buf := buf[32:72]
		if t.Source == nil {
			t.Source = new(phase0.Checkpoint)
		}
		if err = t.Source.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Source")
		}
	}
	{ // Field #2 'Target' (static)
		buf := buf[72:112]
		if t.Target == nil {
			t.Target = new(phase0.Checkpoint)
		}
		if err = t.Target.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Target")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BeaconVote.
func (t *BeaconVote) SizeSSZ() (size int) {
	return 112
}

// HashTreeRoot computes the SSZ hash tree root of the *BeaconVote.
func (t *BeaconVote) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BeaconVote using the given hash walker.
func (t *BeaconVote) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconVote)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlockRoot'
		hh.PutBytes(t.BlockRoot[:32])
	}
	{ // Field #1 'Source'
		t := t.Source
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Source")
		}
	}
	{ // Field #2 'Target'
		t := t.Target
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Target")
		}
	}
	hh.Merkleize(idx)
	return nil
}
