// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 72c425ff10f78e4e6b68cb29f872276cc07832980f77845193948b7d04c1ef1a
// Version: v1.3.3 (https://github.com/pk910/dynamic-ssz)
package types

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[Contribution](`ssz-static:"true"`)

// MarshalSSZ marshals the *Contribution to SSZ-encoded bytes.
func (t *Contribution) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *Contribution to SSZ-encoded bytes, appending to the provided buffer.
func (t *Contribution) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(Contribution)
	}
	{ // Static Field #0 'SelectionProofSig'
		dst = append(dst, t.SelectionProofSig[:96]...)
	}
	{ // Static Field #1 'Contribution'
		t := &t.Contribution
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Contribution")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *Contribution from SSZ-encoded bytes.
func (t *Contribution) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 256 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 256)
	}
	if buflen > 256 {
		return sszutils.ErrTrailingDataFn(buflen - 256)
	}
	{ // Field #0 'SelectionProofSig' (static)
		buf := buf[0:96]
		copy(t.SelectionProofSig[:], buf)
	}
	{ // Field #1 'Contribution' (static)
		buf := buf[96:256]
		if err = t.Contribution.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Contribution")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *Contribution.
func (t *Contribution) SizeSSZ() (size int) {
	return 256
}

// HashTreeRoot computes the SSZ hash tree root of the *Contribution.
func (t *Contribution) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *Contribution using the given hash walker.
func (t *Contribution) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(Contribution)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'SelectionProofSig'
		hh.PutBytes(t.SelectionProofSig[:96])
	}
	{ // Field #1 'Contribution'
		t := &t.Contribution
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Contribution")
		}
	}
	hh.Merkleize(idx)
	return nil
}
