// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 4dc16bab83edc3d0678142045aebe3d0b1ef1e16839db4a22a631459248449a9
// Version: v1.3.3 (https://github.com/pk910/dynamic-ssz)
package types

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
	"github.com/ssvlabs/ssv-spec/types/gloas"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[EnvelopeDissemination](`ssz-static:"false"`)

// MarshalSSZ marshals the *EnvelopeDissemination to SSZ-encoded bytes.
func (t *EnvelopeDissemination) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *EnvelopeDissemination to SSZ-encoded bytes, appending to the provided buffer.
func (t *EnvelopeDissemination) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(EnvelopeDissemination)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	// Offset Field #1 'Envelope'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'Envelope'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Envelope
		if t == nil {
			t = new(gloas.BlindedExecutionPayloadEnvelope)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Envelope")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *EnvelopeDissemination from SSZ-encoded bytes.
func (t *EnvelopeDissemination) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	// Field #1 'Envelope' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset1 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 12), "Envelope:o")
	}
	{ // Field #1 'Envelope' (dynamic)
		buf := buf[offset1:]
		if t.Envelope == nil {
			t.Envelope = new(gloas.BlindedExecutionPayloadEnvelope)
		}
		if err = t.Envelope.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Envelope")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *EnvelopeDissemination.
func (t *EnvelopeDissemination) SizeSSZ() (size int) {
	if t == nil {
		t = new(EnvelopeDissemination)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'Envelope' offset (4 bytes)
	size += 12
	{ // Dynamic field #1 'Envelope'
		size += t.Envelope.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *EnvelopeDissemination.
func (t *EnvelopeDissemination) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *EnvelopeDissemination using the given hash walker.
func (t *EnvelopeDissemination) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(EnvelopeDissemination)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'Envelope'
		t := t.Envelope
		if t == nil {
			t = new(gloas.BlindedExecutionPayloadEnvelope)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Envelope")
		}
	}
	hh.Merkleize(idx)
	return nil
}
