// Code generated by fastssz. DO NOT EDIT.
// Hash: 7933fddd7495efd1cdf80394fb65f95fcada81441608b813ce76dafce56b005c
// Version: 0.1.3
package types

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
	"github.com/ssvlabs/ssv-spec/types/gloas"
)

// MarshalSSZ ssz marshals the EnvelopeDissemination object
func (e *EnvelopeDissemination) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the EnvelopeDissemination object to a target array
func (e *EnvelopeDissemination) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(e.Slot))

	// Offset (1) 'Envelope'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Envelope'
	if dst, err = e.Envelope.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the EnvelopeDissemination object
func (e *EnvelopeDissemination) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Slot'
	e.Slot = phase0.Slot(ssz.UnmarshallUint64(buf[0:8]))

	// Offset (1) 'Envelope'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Envelope'
	{
		buf = tail[o1:]
		if e.Envelope == nil {
			e.Envelope = new(gloas.BlindedExecutionPayloadEnvelope)
		}
		if err = e.Envelope.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the EnvelopeDissemination object
func (e *EnvelopeDissemination) SizeSSZ() (size int) {
	size = 12

	// Field (1) 'Envelope'
	if e.Envelope == nil {
		e.Envelope = new(gloas.BlindedExecutionPayloadEnvelope)
	}
	size += e.Envelope.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the EnvelopeDissemination object
func (e *EnvelopeDissemination) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the EnvelopeDissemination object with a hasher
func (e *EnvelopeDissemination) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(uint64(e.Slot))

	// Field (1) 'Envelope'
	if err = e.Envelope.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the EnvelopeDissemination object
func (e *EnvelopeDissemination) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(e)
}
