package types

//go:generate rm -f ./operator_encoding.go
//go:generate go run github.com/ferranbt/fastssz/sszgen --path operator.go --include ./committee_id.go,./domain_type.go --exclude-objs OperatorID

//go:generate rm -f ./share_encoding.go
//go:generate go run github.com/ferranbt/fastssz/sszgen --path share.go --include $GOPATH/pkg/mod/github.com/attestantio/go-eth2-client@v0.27.0/spec/phase0,./operator.go,./messages.go,./signer.go,./domain_type.go

//go:generate rm -f ./messages_encoding.go
//go:generate go run github.com/ferranbt/fastssz/sszgen --path messages.go --include ./operator.go --exclude-objs ValidatorPK,MessageID,MsgType,ShareValidatorPK

//go:generate rm -f ./beacon_types_encoding.go
//go:generate go run github.com/ferranbt/fastssz/sszgen --path beacon_types.go --include $GOPATH/pkg/mod/github.com/attestantio/go-eth2-client@v0.27.0/spec/phase0 --exclude-objs BeaconNetwork,BeaconRole,CommitteeDuty,AggregatorCommitteeDuty

//go:generate rm -f ./partial_sig_message_encoding.go
//go:generate go run github.com/ferranbt/fastssz/sszgen --path partial_sig_message.go --include $GOPATH/pkg/mod/github.com/attestantio/go-eth2-client@v0.27.0/spec/phase0,./signer.go,./operator.go --exclude-objs PartialSigMsgType

// Consensus-data types embed go-eth2-client composite types, which moved to dynamic-ssz;
// their encoders are generated by pk910/dynamic-ssz (the rest of this package stays on fastssz).
// EnvelopeDissemination is here too: it nests the progressive Gloas blinded envelope (SIP #94 §6).
//go:generate go tool dynssz-gen -config generate_cd.yaml
