// Code generated by fastssz. DO NOT EDIT.
// Hash: 5fc6cc4814535a3672ad42fd6ab6ee0dac3155181e3063b3250f6c1761685937
// Version: 0.1.3
package types

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Share object
func (s *Share) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the Share object to a target array
func (s *Share) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(522)

	// Field (0) 'ValidatorIndex'
	dst = ssz.MarshalUint64(dst, uint64(s.ValidatorIndex))

	// Field (1) 'ValidatorPubKey'
	dst = append(dst, s.ValidatorPubKey[:]...)

	// Field (2) 'OwnValidatorShare'
	if dst, err = s.OwnValidatorShare.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'SharePubKey'
	if size := len(s.SharePubKey); size != 48 {
		err = ssz.ErrBytesLengthFn("Share.SharePubKey", size, 48)
		return
	}
	dst = append(dst, s.SharePubKey...)

	// Offset (4) 'Committee'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.Committee) * 56

	// Field (5) 'Quorum'
	dst = ssz.MarshalUint64(dst, s.Quorum)

	// Field (6) 'DomainType'
	dst = append(dst, s.DomainType[:]...)

	// Field (7) 'FeeRecipientAddress'
	dst = append(dst, s.FeeRecipientAddress[:]...)

	// Field (8) 'Graffiti'
	if size := len(s.Graffiti); size != 32 {
		err = ssz.ErrBytesLengthFn("Share.Graffiti", size, 32)
		return
	}
	dst = append(dst, s.Graffiti...)

	// Field (4) 'Committee'
	if size := len(s.Committee); size > 13 {
		err = ssz.ErrListTooBigFn("Share.Committee", size, 13)
		return
	}
	for ii := 0; ii < len(s.Committee); ii++ {
		if dst, err = s.Committee[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Share object
func (s *Share) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 522 {
		return ssz.ErrSize
	}

	tail := buf
	var o4 uint64

	// Field (0) 'ValidatorIndex'
	s.ValidatorIndex = phase0.ValidatorIndex(ssz.UnmarshallUint64(buf[0:8]))

	// Field (1) 'ValidatorPubKey'
	copy(s.ValidatorPubKey[:], buf[8:56])

	// Field (2) 'OwnValidatorShare'
	if err = s.OwnValidatorShare.UnmarshalSSZ(buf[56:406]); err != nil {
		return err
	}

	// Field (3) 'SharePubKey'
	if cap(s.SharePubKey) == 0 {
		s.SharePubKey = make([]byte, 0, len(buf[406:454]))
	}
	s.SharePubKey = append(s.SharePubKey, buf[406:454]...)

	// Offset (4) 'Committee'
	if o4 = ssz.ReadOffset(buf[454:458]); o4 > size {
		return ssz.ErrOffset
	}

	if o4 < 522 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (5) 'Quorum'
	s.Quorum = ssz.UnmarshallUint64(buf[458:466])

	// Field (6) 'DomainType'
	copy(s.DomainType[:], buf[466:470])

	// Field (7) 'FeeRecipientAddress'
	copy(s.FeeRecipientAddress[:], buf[470:490])

	// Field (8) 'Graffiti'
	if cap(s.Graffiti) == 0 {
		s.Graffiti = make([]byte, 0, len(buf[490:522]))
	}
	s.Graffiti = append(s.Graffiti, buf[490:522]...)

	// Field (4) 'Committee'
	{
		buf = tail[o4:]
		num, err := ssz.DivideInt2(len(buf), 56, 13)
		if err != nil {
			return err
		}
		s.Committee = make([]*ShareMember, num)
		for ii := 0; ii < num; ii++ {
			if s.Committee[ii] == nil {
				s.Committee[ii] = new(ShareMember)
			}
			if err = s.Committee[ii].UnmarshalSSZ(buf[ii*56 : (ii+1)*56]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Share object
func (s *Share) SizeSSZ() (size int) {
	size = 522

	// Field (4) 'Committee'
	size += len(s.Committee) * 56

	return
}

// HashTreeRoot ssz hashes the Share object
func (s *Share) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the Share object with a hasher
func (s *Share) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ValidatorIndex'
	hh.PutUint64(uint64(s.ValidatorIndex))

	// Field (1) 'ValidatorPubKey'
	hh.PutBytes(s.ValidatorPubKey[:])

	// Field (2) 'OwnValidatorShare'
	if err = s.OwnValidatorShare.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'SharePubKey'
	if size := len(s.SharePubKey); size != 48 {
		err = ssz.ErrBytesLengthFn("Share.SharePubKey", size, 48)
		return
	}
	hh.PutBytes(s.SharePubKey)

	// Field (4) 'Committee'
	{
		subIndx := hh.Index()
		num := uint64(len(s.Committee))
		if num > 13 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range s.Committee {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 13)
	}

	// Field (5) 'Quorum'
	hh.PutUint64(s.Quorum)

	// Field (6) 'DomainType'
	hh.PutBytes(s.DomainType[:])

	// Field (7) 'FeeRecipientAddress'
	hh.PutBytes(s.FeeRecipientAddress[:])

	// Field (8) 'Graffiti'
	if size := len(s.Graffiti); size != 32 {
		err = ssz.ErrBytesLengthFn("Share.Graffiti", size, 32)
		return
	}
	hh.PutBytes(s.Graffiti)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Share object
func (s *Share) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the ShareMember object
func (s *ShareMember) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the ShareMember object to a target array
func (s *ShareMember) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'SharePubKey'
	if size := len(s.SharePubKey); size != 48 {
		err = ssz.ErrBytesLengthFn("ShareMember.SharePubKey", size, 48)
		return
	}
	dst = append(dst, s.SharePubKey...)

	// Field (1) 'Signer'
	dst = ssz.MarshalUint64(dst, uint64(s.Signer))

	return
}

// UnmarshalSSZ ssz unmarshals the ShareMember object
func (s *ShareMember) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 56 {
		return ssz.ErrSize
	}

	// Field (0) 'SharePubKey'
	if cap(s.SharePubKey) == 0 {
		s.SharePubKey = make([]byte, 0, len(buf[0:48]))
	}
	s.SharePubKey = append(s.SharePubKey, buf[0:48]...)

	// Field (1) 'Signer'
	s.Signer = OperatorID(ssz.UnmarshallUint64(buf[48:56]))

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ShareMember object
func (s *ShareMember) SizeSSZ() (size int) {
	size = 56
	return
}

// HashTreeRoot ssz hashes the ShareMember object
func (s *ShareMember) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the ShareMember object with a hasher
func (s *ShareMember) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'SharePubKey'
	if size := len(s.SharePubKey); size != 48 {
		err = ssz.ErrBytesLengthFn("ShareMember.SharePubKey", size, 48)
		return
	}
	hh.PutBytes(s.SharePubKey)

	// Field (1) 'Signer'
	hh.PutUint64(uint64(s.Signer))

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ShareMember object
func (s *ShareMember) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
