// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: gg20/types/messages.proto

package types

import (
	types "github.com/bloxapp/ssv-spec/dkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Round1Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *Round1Msg) Reset() {
	*x = Round1Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round1Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Msg) ProtoMessage() {}

func (x *Round1Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Msg.ProtoReflect.Descriptor instead.
func (*Round1Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Round1Msg) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type Round2Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decommitment [][]byte `protobuf:"bytes,1,rep,name=decommitment,proto3" json:"decommitment,omitempty"`
	BlindFactor  []byte   `protobuf:"bytes,2,opt,name=blind_factor,json=blindFactor,proto3" json:"blind_factor,omitempty"`
}

func (x *Round2Msg) Reset() {
	*x = Round2Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round2Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Msg) ProtoMessage() {}

func (x *Round2Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Msg.ProtoReflect.Descriptor instead.
func (*Round2Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Round2Msg) GetDecommitment() [][]byte {
	if x != nil {
		return x.Decommitment
	}
	return nil
}

func (x *Round2Msg) GetBlindFactor() []byte {
	if x != nil {
		return x.BlindFactor
	}
	return nil
}

type Round3Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Share []byte `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
}

func (x *Round3Msg) Reset() {
	*x = Round3Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round3Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Msg) ProtoMessage() {}

func (x *Round3Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Msg.ProtoReflect.Descriptor instead.
func (*Round3Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Round3Msg) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

type Round4Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment        []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	PubKey            []byte `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	ChallengeResponse []byte `protobuf:"bytes,3,opt,name=challenge_response,json=challengeResponse,proto3" json:"challenge_response,omitempty"`
}

func (x *Round4Msg) Reset() {
	*x = Round4Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round4Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Msg) ProtoMessage() {}

func (x *Round4Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Msg.ProtoReflect.Descriptor instead.
func (*Round4Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Round4Msg) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *Round4Msg) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *Round4Msg) GetChallengeResponse() []byte {
	if x != nil {
		return x.ChallengeResponse
	}
	return nil
}

type KeygenMsgBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round1 *Round1Msg `protobuf:"bytes,1,opt,name=round1,proto3" json:"round1,omitempty"`
	Round2 *Round2Msg `protobuf:"bytes,2,opt,name=round2,proto3" json:"round2,omitempty"`
	Round3 *Round3Msg `protobuf:"bytes,3,opt,name=round3,proto3" json:"round3,omitempty"`
	Round4 *Round4Msg `protobuf:"bytes,4,opt,name=round4,proto3" json:"round4,omitempty"`
}

func (x *KeygenMsgBody) Reset() {
	*x = KeygenMsgBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMsgBody) ProtoMessage() {}

func (x *KeygenMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMsgBody.ProtoReflect.Descriptor instead.
func (*KeygenMsgBody) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{4}
}

func (x *KeygenMsgBody) GetRound1() *Round1Msg {
	if x != nil {
		return x.Round1
	}
	return nil
}

func (x *KeygenMsgBody) GetRound2() *Round2Msg {
	if x != nil {
		return x.Round2
	}
	return nil
}

func (x *KeygenMsgBody) GetRound3() *Round3Msg {
	if x != nil {
		return x.Round3
	}
	return nil
}

func (x *KeygenMsgBody) GetRound4() *Round4Msg {
	if x != nil {
		return x.Round4
	}
	return nil
}

//
// It has the same shape as base.Message except the data is parsed into KeygenMsgBody
type ParsedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *types.MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body      *KeygenMsgBody       `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature []byte               `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ParsedMessage) Reset() {
	*x = ParsedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedMessage) ProtoMessage() {}

func (x *ParsedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedMessage.ProtoReflect.Descriptor instead.
func (*ParsedMessage) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ParsedMessage) GetHeader() *types.MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedMessage) GetBody() *KeygenMsgBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ParsedMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_gg20_types_messages_proto protoreflect.FileDescriptor

var file_gg20_types_messages_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x67, 0x32, 0x30, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x73, 0x76,
	0x2e, 0x67, 0x67, 0x32, 0x30, 0x1a, 0x18, 0x64, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2b, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x52, 0x0a, 0x09,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x0c, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x22, 0x21, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x22, 0x73, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x4d, 0x73, 0x67,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x0d, 0x4b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x73, 0x76,
	0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x73, 0x67, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67,
	0x32, 0x30, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x32, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x33, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x34, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x22, 0x90,
	0x01, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x34, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x64, 0x6b, 0x67, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e,
	0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x67, 0x32, 0x30, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gg20_types_messages_proto_rawDescOnce sync.Once
	file_gg20_types_messages_proto_rawDescData = file_gg20_types_messages_proto_rawDesc
)

func file_gg20_types_messages_proto_rawDescGZIP() []byte {
	file_gg20_types_messages_proto_rawDescOnce.Do(func() {
		file_gg20_types_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_gg20_types_messages_proto_rawDescData)
	})
	return file_gg20_types_messages_proto_rawDescData
}

var file_gg20_types_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gg20_types_messages_proto_goTypes = []interface{}{
	(*Round1Msg)(nil),           // 0: ssv.gg20.Round1Msg
	(*Round2Msg)(nil),           // 1: ssv.gg20.Round2Msg
	(*Round3Msg)(nil),           // 2: ssv.gg20.Round3Msg
	(*Round4Msg)(nil),           // 3: ssv.gg20.Round4Msg
	(*KeygenMsgBody)(nil),       // 4: ssv.gg20.KeygenMsgBody
	(*ParsedMessage)(nil),       // 5: ssv.gg20.ParsedMessage
	(*types.MessageHeader)(nil), // 6: ssv.dkg.types.MessageHeader
}
var file_gg20_types_messages_proto_depIdxs = []int32{
	0, // 0: ssv.gg20.KeygenMsgBody.round1:type_name -> ssv.gg20.Round1Msg
	1, // 1: ssv.gg20.KeygenMsgBody.round2:type_name -> ssv.gg20.Round2Msg
	2, // 2: ssv.gg20.KeygenMsgBody.round3:type_name -> ssv.gg20.Round3Msg
	3, // 3: ssv.gg20.KeygenMsgBody.round4:type_name -> ssv.gg20.Round4Msg
	6, // 4: ssv.gg20.ParsedMessage.header:type_name -> ssv.dkg.types.MessageHeader
	4, // 5: ssv.gg20.ParsedMessage.body:type_name -> ssv.gg20.KeygenMsgBody
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gg20_types_messages_proto_init() }
func file_gg20_types_messages_proto_init() {
	if File_gg20_types_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gg20_types_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Round1Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Round2Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Round3Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Round4Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeygenMsgBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gg20_types_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gg20_types_messages_proto_goTypes,
		DependencyIndexes: file_gg20_types_messages_proto_depIdxs,
		MessageInfos:      file_gg20_types_messages_proto_msgTypes,
	}.Build()
	File_gg20_types_messages_proto = out.File
	file_gg20_types_messages_proto_rawDesc = nil
	file_gg20_types_messages_proto_goTypes = nil
	file_gg20_types_messages_proto_depIdxs = nil
}
