name: Generate Spec Tests
description: Set up Go environment and generate spec test JSON files into ../spec-tests

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: 1.22.x

    - name: Get Dependencies
      shell: bash
      run: go get -v -t -d ./...

    - name: Create spec-tests output directory
      shell: bash
      run: mkdir -p ../spec-tests

    - name: Generate JSONs
      shell: bash
      run: make generate-jsons
