package testdoc

const MsgValidationSpecTestType = "P2P message validation: validation of pubsub decoding, signed-message verification, and runner acceptance rules"

const MalformedPubsubPayloadDoc = "Rejects malformed pubsub payloads that cannot decode into SignedSSVMessage."
const NoSignersDoc = "Rejects SignedSSVMessages that carry no operator signers."
const NoSignaturesDoc = "Rejects SignedSSVMessages that carry no signatures."
const EmptySignatureDoc = "Rejects SignedSSVMessages that contain an empty signature entry."
const SignatureCountMismatchDoc = "Rejects SignedSSVMessages whose signer count does not match the signature count."
const ZeroSignerDoc = "Rejects SignedSSVMessages that contain signer ID 0."
const NonUniqueSignersDoc = "Rejects SignedSSVMessages that contain duplicate operator signer IDs."
const UnsupportedSSVMessageTypeDoc = "Rejects SignedSSVMessages that carry an unsupported top-level SSV message type."
const ValidExistingInstanceConsensusDoc = "Accepts a valid consensus proposal for an already running QBFT instance."
const UnknownInstanceConsensusDoc = "Rejects a consensus message for a height that has no stored instance."
const InvalidConsensusSignatureDoc = "Rejects a structurally valid consensus message whose outer operator signature does not match the signer ID."
const WrongConsensusIdentifierDoc = "Rejects a consensus message whose QBFT identifier does not belong to the runner controller."
const FutureConsensusMultiSignerDoc = "Rejects future non-decided consensus gossip when it carries more than one signer."
const ValidFutureDecidedConsensusDoc = "Accepts a future decided consensus message that carries quorum signatures and valid full data."
const DecidedConsensusBadFullDataDoc = "Rejects a decided consensus message when FullData does not hash to the commit root."
const ValidPreConsensusPartialSignatureDoc = "Accepts a valid aggregator-committee pre-consensus partial signature message."
const InvalidPreConsensusPartialSignatureSignatureDoc = "Rejects a pre-consensus partial signature message whose outer RSA signature does not match the declared operator signer."
const PreConsensusWithoutRunningDutyDoc = "Rejects pre-consensus partial signatures when the runner has no active duty."
const PreConsensusSignerMismatchDoc = "Rejects pre-consensus partial signatures when the outer signer differs from the inner partial-signature signer."
const PreConsensusPastSlotDoc = "Rejects pre-consensus partial signatures whose slot is older than the running duty slot."
const PreConsensusFutureSlotDoc = "Rejects pre-consensus partial signatures whose slot is ahead of the running duty slot."
const PreConsensusUnknownValidatorIndexDoc = "Rejects non-aggregator pre-consensus partial signatures when the runner has no share for the validator index."
const MultiSignerPartialSignatureDoc = "Rejects partial-signature gossip that carries more than one outer operator signer."
const ValidPostConsensusPartialSignatureDoc = "Accepts a valid post-consensus partial signature message after the runner has a decided value."
const PostConsensusWithoutDecidedValueDoc = "Rejects post-consensus partial-signature messages when the runner has no decided value yet."
const PostConsensusWithoutRunningInstanceDoc = "Rejects post-consensus partial signatures when the runner has decided value bytes but no running consensus instance."
const PostConsensusNotDecidedDoc = "Rejects post-consensus partial signatures when the running QBFT instance exists but has not decided yet."
