name: 'Label stale PRs and Issues'
on:
  schedule:
    # Runs at 1:30 AM every day
    - cron: '30 1 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0
        with:
          days-before-stale: 60
          days-before-close: -1
          stale-pr-message: 'This pull request has been marked as stale due to 60 days of inactivity.'
          stale-issue-message: 'This issue has been marked as stale due to 60 days of inactivity.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          operations-per-run: 100
          # Enable statistics in the logs
          enable-statistics: true