name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x

      - name: Get Dependencies
        run: go get -v -t -d ./...

      - name: Generate JSONs
        run: make generate-jsons

      - name: Test
        run: make test
