name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Generate spec tests
        uses: ./.github/actions/generate-spec-tests

      - name: Test
        run: make test
