name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate spec tests
        uses: ./.github/actions/generate-spec-tests

      - name: Test
        run: make test
